# Before your start:
- Read the README.md file
- Comment as much as you can and use the resources in the README.md file
- Happy learning!

# Challenge 1 - Matrix Functions

#### We would like to create our own matrix. To make life simple for us, we can represent matrices as a list of lists. For the sake of simplicity, we will assume that the maximum number of dimensions a matrix will have is 2.

The most basic thing we would like to do with two matrices is to add them together. To add two matrices, we must perform a number of checks. The first check we would like to perform is whether the matrix is two dimesional. This is because we want to limit ourselves to two dimensional matrices to simplify our problem. In the cell below write a function that checks is a matrix is two dimesional. 

In [3]:
import numpy as np
mat = [[1,2,3], [4,5,6]]

def twodim(mat):
    # This function takes a list of lists and checks that it is of depth 2. 
    # If the depth is not 2, either return false or return informative errors that let the user know the depth of the list.
    # Input: nested list
    # Output: Boolean (or error)
    # Sample Input: [[1,2,3], [4,5,6]]
    # Sample Output: True
    
    # Your Code Here:
    if len(np.shape(mat)) == 2:
        return True
    else:
        return False

print(twodim(mat))  
    

True


In [30]:
print(twodim([[1,2], [1,2,3],[1,2,3]]))
"""En este caso la función twodim no reconoce a la lista de listas como de 2d ya que la tupla que se genera
con la función a.shape de numpy es de la forma (3,'null'). Creo que esto se podría resolver llenando los 
los valores nulos con pandas y luego ejecutando el a.shape"""

False


# Bonus Challenge 1 - Write the function recursively

Rewrite the `twodim` function using recursion. 
Read more about recursion [here](https://www.cs.utah.edu/~germain/PPS/Topics/recursion.html)

Hint: stop your recursion when there are no more lists, this wil be the depth of your matrix. Check that this depth is equal to 2.
Second Hint: At every level of the recursion, use the filter function to keep only the members of the list that are lists.

In [38]:
def twodimrecursive(mat):
    pass
    # Your code here:
###No tengo ni idea...

In [39]:
twodimrecursive([[1,2,3],[1,2]])
###No entiendo este ejercicio

#### Next, we will write a function that checks for the number of rows and columns of a matrix. 

Recall that the outer list will tell us the number of rows and the inner lists will tell us the number of columns. Make sure that all inner lists are of the same length.

In [5]:
mat = [[1,2,3],[4,5,6]]

def rowcolumn(mat):
    # This function takes a list of lists and returns the size of the rows and the columns 
    # Input: list of lists
    # Output: Tuple of rows and columns
    #
    # Sample input: [[1,2,3],[4,5,6]]
    # Sample Output: (2, 3)
    
    # Your code here:
    return (np.shape(mat))

print(rowcolumn(mat))

(2, 3)


In [6]:
rowcolumn([[1,2,3,4], [1,2,3,4],[1,2,3,4]])

(3, 4)

#### Our next step is to write a function that compares two matrices and tells us whether they are of equal size.

In this function we will check whether the number of rows and number of columns is the same.

In [7]:
mat1 = [[1,2,3],[4,5,6]]
mat2 = [[7,8,9],[10,11,12]]

def compare(mat1, mat2):
    # This function takes a two lists of lists and checks whether they have the same number of rows and columns
    # Input: two list of lists
    # Output: True or False
    #
    # Sample input: [[1,2,3],[4,5,6]], [[7,8,9], [10,11,12]]
    # Sample Output: True
    
    # Your code here:
    if np.shape(mat1) == np.shape(mat2):
        return True
    else:
        return False
    
print(compare(mat1, mat2))

True


In [8]:
compare([[1,2,3],[4,5,6]], [[7,8,9], [10,11,12]])

True

#### Now that we have all the tools we need, write a function that adds two matrices together. 

Remember that a matrix is represented as a list of lists. Therefore, we must add each element in the list. The plus symbol is used for concatenating two lists and not for adding every element in two lists.

In [18]:
mat1 = [[1,2,3],[4,5,6]]
mat2 = [[7,8,9], [10,11,12]]

def addition(mat1, mat2):
    # This function takes a two lists of lists and adds each cell together
    # Input: two list of lists
    # Output: one summed list of lists
    #
    # Sample input: [[1,2,3],[4,5,6]], [[7,8,9], [10,11,12]]
    # Sample Output: [[8,10,12],[14,16,18]]
    
    # Your code here:
    return np.sum([mat1, mat2], axis=0)

print(addition(mat1,mat2))

[[ 8 10 12]
 [14 16 18]]


In [19]:
addition([[1,2,3],[4,5,6]], [[7,8,9], [10,11,12]])

array([[ 8, 10, 12],
       [14, 16, 18]])

# Challenge 2 - Creating the Class

In the cell below, you will be creating the class Matrix2D. Use the functions you have written above and tweak them according to the instructions in the comments. You got this!

In [36]:
import numpy as np

class Matrix2D:
    # First, we will write the __init__ function. 
    # In this function, we will initialize rows and the columns using the matrix that we have passed to the class.

    def __init__(self, mat):
        # Assign mat to self.mat
        # Assign rows and cols to self.rows and self.cols
        # To find the rows and the cols, use the rowcolumn function and pass self.mat to the function.
        # Since the rowcolumn function is now a member of the class, make sure to refer to the function as self.rowcolumn
        
        # Your code here:
        
        self.mat = mat
        self.rows = (self.rowcolumn(self.mat))
        self.columns = (self.rowcolumn(self.mat))
    
    # Insert the twodim function here.
    # The only change you need to make is that now we are passing self and mat to the function (make sure self is first).
    
    # Your code here:
    
    def twodim(self, mat):
        if len(np.shape(mat)) == 2:
            return True
        else:
            return False

    # Insert the rowcolumn function here.
    # The changes you need to make: 
    # 1. The function now takes self and mat as arguments (make sure to pass self first).
    # 2. Any reference to twodim will be changed to self.twodim since this function is a member of the class and takes self 
###No entiendo para que vale este comentario sobre 'twodim'    
    # Your code here:

    def rowcolumn(self, mat):
        return np.shape(mat)
    
    # Insert the compare function here
    # Add self as the first argument passed to the function
    
    # Your code here:

    def compare(self, mat1, mat2):
        return (np.shape(mat1)==np.shape(mat2))

    # Insert the addition function here
    # This function now takes self and matrix (another matrix of the Matrix2D class)
    # Change the compare function to self.compare 
    # Change any reference to mat1 and mat2 to self.mat and matrix.mat respectively
    # Return your result as a Matrix2D(result). This will ensure that we return a new matrix and not a list of lists.
    
    # Your code here:
###No entiendo que significan todas estas instrucciones para crear el método addition
    def addition(self, matrix):
        return Matrix2D(np.sum([self.mat, matrix.mat], axis=0))

###No tengo idea de la diferencia entre hacer return Matrix2D(np.sum([self.mat, matrix.mat], axis=0)) y 
### Matrix2D = np.sum([self.mat, matrix.mat], axis=0) y luego return Matrix2D. El print es el mismo:
###<class '__main__.Matrix2D'> pero luego no funciona cuando se hace la operación en la siguiente cell


In [35]:
Matrix2D([[1,2,3],[4,5,6]]).addition(Matrix2D([[7,8,9],[10,11,12]])).mat
###No tengo ni idea de que se está haciendo aqui...


array([[ 8, 10, 12],
       [14, 16, 18]])

# Bonus Challenge 2 - Transpose Function

#### Write a function that transposes the matrix and add it to your class.

You can read more about the transpose of a matrix [here](https://en.wikipedia.org/wiki/Transpose).

Hint: Use the zip function. Read about it [here](https://docs.python.org/3.3/library/functions.html#zip)

Second Hint: Read about the asterisk in Python [here](https://docs.python.org/3/reference/expressions.html#expression-lists)

In [25]:
def transpose(mat):
    # This function takes a list of lists and returns a transposed list of lists.
    # Input: list of lists
    # Output: list of lists
    
    # Sample Input: [[1,2,3],[4,5,6]]
    # Sample Output: [[1,4], [2,5], [3,6]]
    
    # Your code here:
    return np.array(mat).T
#Se convierte la lista de listas 'mat' en un array de numpy y se transpone con la función .T
print(transpose(mat))

[[1 4]
 [2 5]
 [3 6]]


In [26]:
transpose([[1,2,3],[4,5,6]])

array([[1, 4],
       [2, 5],
       [3, 6]])